apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techchallengeapp
  name: frontend-deployment
  namespace: techchallengeapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: techchallengeapp
status:
  loadBalancer: {}
